name: Wastepaper
markdown: kramdown
url: http://wastepaper.website
baseurl: /
paginate: 3
excerpt_separator: "<!-- more -->"
permalink: pretty
gems:
  - jekyll-sitemap
kramdown:
  parse_block_html: true
