name: Wastepaper
markdown: kramdown
url: https://wastepaper.website
baseurl: ""
paginate: 3
excerpt_separator: "<!-- more -->"
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
